export const brands = [
  {
    "id": 1,
    "nombre": "Audi",
    "modelos": [
      "A5",
      "A3",
      "A4",
      "A6",
      "S3",
      "S4",
      "TT",
      "A1",
      "TTS",
      "A1 1.4 T",
      "Q7",
      "Q5",
      "Q3",
      "Q2"
    ]
  },
  {
    "id": 2,
    "nombre": "BMW",
    "modelos": [
      "Serie 6",
      "Serie 7",
      "Z4",
      "M6",
      "Serie 1",
      "Serie 3",
      "Serie 5",
      "Serie 8",
      "1800",
      "M",
      "Serie 4",
      "Serie 2",
      "M235",
      "428i",
      "i",
      "1M",
      "M4",
      "M3",
      "M2",
      "X6",
      "X1",
      "X3",
      "X5",
      "X4",
      "X2"
    ]
  },
  {
    "id": 3,
    "nombre": "Chevrolet",
    "modelos": [
      "Alto",
      "Astra",
      "Bel Air",
      "Camaro",
      "Aveo",
      "Cavalier",
      "Celebrity",
      "Citation",
      "Corsa",
      "Chevy",
      "Epica",
      "Esteem",
      "Impala",
      "Malibu",
      "Monza",
      "Optra",
      "Spark",
      "Sprint",
      "Style",
      "Line",
      "Swift",
      "Wagon R+",
      "Sail",
      "Buick",
      "Cruze",
      "39",
      "Cobalt",
      "Sonic",
      "Onix",
      "Beat",
      "Vivant",
      "Blazer 4x2",
      "Captiva",
      "Tahoe",
      "HHR",
      "Courier",
      "Zafira",
      "Blazer",
      "4x4",
      "Grand",
      "Vitara",
      "Grand Blazer",
      "Rodeo",
      "Suburban",
      "Trail",
      "Blazer",
      "Traverse",
      "Orlando",
      "Tracker",
      "Equinox",
      "Jimny",
      "Samurai",
      "Trooper",
      "Vitara",
      "FSR",
      "FVR",
      "FTR",
      "NNR",
      "Cheyenne",
      "C30",
      "3100",
      "Luv",
      "Brigadier",
      "C70",
      "Carry",
      "NHR",
      "NPR",
      "NKR",
      "Super",
      "Brigadier",
      "Super",
      "Carry",
      "Kodiak",
      "NQR",
      "FRR",
      "FVZ",
      "N300",
      "Luv",
      "D-max",
      "DMAX",
      "Super",
      "Carry",
      "NQR",
      "FRR",
      "Carry",
      "CHR",
      "LV",
      "NKR",
      "NPR",
      "Luv",
      "D-max",
      "SSR",
      "Luv Dmax",
      "N300",
      "Apache",
      "C10",
      "C30",
      "Cheyenne",
      "Luv 1.6",
      "Luv 2.2",
      "Luv 2.3",
      "Luv 2.5",
      "Colorado",
      "Luv 2.8",
      "Silverado",
      "Optra",
      "Spark",
      "Corsa",
      "Taxi",
      "Chevette",
      "Chevytaxi",
      "7:24",
      "ChevyVan",
      "ChevyWagon",
      "Super",
      "Carry",
      "N200",
      "N300"
    ]
  }]